"""baseline

Revision ID: 96f7e0807499
Revises: 
Create Date: 2026-09-11 16:20:24.015366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f7e0807499'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements_channel',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('extra_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('lower_bound', sa.Integer(), nullable=False),
    sa.Column('upper_bound', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('guild_config',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('host_role',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('log_channel',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('reminderpings',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('ping', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('seeking_channel',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('speedtask',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('speedtaskdesc',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('speedtasklength',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('speedtaskreminders',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('reminder1', sa.Integer(), nullable=True),
    sa.Column('reminder2', sa.Integer(), nullable=True),
    sa.Column('reminder3', sa.Integer(), nullable=True),
    sa.Column('reminder4', sa.Integer(), nullable=True),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('submission_channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_channel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_channel_comp'), ['comp'], unique=False)

    op.create_table('submission_file_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('submissions',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('ghost_time', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.Integer(), nullable=False),
    sa.Column('dq', sa.Boolean(), nullable=True),
    sa.Column('dq_reason', sa.String(), nullable=True),
    sa.Column('character', sa.String(), nullable=True),
    sa.Column('vehicle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('submitter_role',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('speed_task', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.Integer(), nullable=False),
    sa.Column('is_released', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_channel',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comp', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('comp')
    )
    op.create_table('teams',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=False),
    sa.Column('user2', sa.Integer(), nullable=True),
    sa.Column('user3', sa.Integer(), nullable=True),
    sa.Column('user4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('userbase',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userbase')
    op.drop_table('teams')
    op.drop_table('tasks_channel')
    op.drop_table('tasks')
    op.drop_table('submitter_role')
    op.drop_table('submissions')
    op.drop_table('submission_file_config')
    with op.batch_alter_table('submission_channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_channel_comp'))

    op.drop_table('submission_channel')
    op.drop_table('speedtaskreminders')
    op.drop_table('speedtasklength')
    op.drop_table('speedtaskdesc')
    op.drop_table('speedtask')
    op.drop_table('seeking_channel')
    op.drop_table('reminderpings')
    op.drop_table('log_channel')
    op.drop_table('host_role')
    op.drop_table('guild_config')
    op.drop_table('extra_setting')
    op.drop_table('announcements_channel')
    # ### end Alembic commands ###
